version: '3.8'

services:

  reverseproxy:
    restart: always
    build:
      context: reverse-proxy/
      dockerfile: ./Dockerfile.dev
    depends_on:
      - api
      - frontend
    volumes:
      - ./reverse-proxy/log:/var/log/nginx
    ports:
      - 3000:80

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
  api:
    build: 
      context: api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/src:/app/src
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DB=repas
      - TOKEN_KEY=testazertyuiop
      - REDIS_HOST=redis  # Add this line
      - REDIS_PORT=6379   # Add this line
      - EDAMAM_ID=01c306cf
      - EDAMAM_KEY=6179f34f1acea7368bcd5d4020b90b0c
    depends_on:
      - mongodb
      - redis

  mongodb:
    container_name: repas_mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=repas
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    ports:
    - "6379:6379"
volumes:
  mongodb_data:

