# Stage 1: Build Stage
FROM node:14 as builder

WORKDIR /app
COPY package*.json ./

RUN npm ci --only=production
COPY . .

# Stage 2: Production Stage
FROM node:14-alpine

WORKDIR /app

COPY package*.json ./

# Install production dependencies only
RUN npm ci --only=production

# Copy built files from the builder stage
COPY --from=builder /app/dist ./dist

# Expose the port
EXPOSE 80

# Command to run the application
CMD ["node", "dist/app.bundle.min.cjs"]
